In [ ]:
import numpy as np
arr1=np.arange(9).reshape(3,3)
print(np.max(arr1))

8


In [ ]:
for each in range(0,8,2):
  print(each)

0
2
4
6


In [ ]:
A_prev = np.random.randn(1,3)
print(A_prev)

[[-0.7422735  0.7536983 -0.1695517]]


In [ ]:
arr1=np.arange(3,11).reshape(2,4)
arr2=np.arange(12,20).reshape(2,4)
print(arr1)
print(arr2)
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 3  4  5  6]
 [ 7  8  9 10]]
[[12 13 14 15]
 [16 17 18 19]]
[[ 3  4  5  6 12 13 14 15]
 [ 7  8  9 10 16 17 18 19]]


In [ ]:
vote_list=["Thet Naing Tun", "Zaw Lwin Oo"]
for each in vote_list:
  print("Name: {}, I will comminting".format(each))

Name: Thet Naing Tun, I will comminting
Name: Zaw Lwin Oo, I will comminting


In [ ]:
import numpy as np
A=np.arange(10).reshape(2,5)
B=(A==7)
print(B)

[[False False False False False]
 [False False  True False False]]


In [ ]:
! pip install -q kaggle

In [1]:
!python --version

Python 3.8.6


In [6]:
!pip list>test.txt

In [ ]:
from google.colab import files

files.upload()

Saving recipes.json to recipes.json


KeyboardInterrupt: ignored

In [ ]:
! mkdir ~/.kaggle

In [ ]:
! cp kaggle.json ~/.kaggle/

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!wget https://www.kaggle.com/sterby/german-recipes-dataset/download


--2020-10-25 15:39:34--  https://www.kaggle.com/sterby/german-recipes-dataset/download
Resolving www.kaggle.com (www.kaggle.com)... 35.244.233.98
Connecting to www.kaggle.com (www.kaggle.com)|35.244.233.98|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /account/login?returnUrl=%2Fsterby%2Fgerman-recipes-dataset%3Fresource%3Ddownload%26downloadHash%3D103cab1ce34ee437b5ea0c17581429ad99fcd3183de99cdc1e4bb46f6949dda9&message=Welcome to Kaggle! Join our community of over 5 million data scientists. Find datasets and code as well as free access to compute on our platform.&titleType=dataset-downloads&showDatasetDownloadSkip=True [following]
--2020-10-25 15:39:34--  https://www.kaggle.com/account/login?returnUrl=%2Fsterby%2Fgerman-recipes-dataset%3Fresource%3Ddownload%26downloadHash%3D103cab1ce34ee437b5ea0c17581429ad99fcd3183de99cdc1e4bb46f6949dda9&message=Welcome%20to%20Kaggle!%20Join%20our%20community%20of%20over%205%20million%20data%20scientists.%20Find%20data

In [ ]:
ls

download  drive/  sample_data/


In [ ]:
!wget https://docs.google.com/spreadsheets/d/1yoHIzDcD62lBmtVf3WheVZuSpW6DwIa03UrPlZIXfiI "test.xlsx"

--2020-10-25 15:45:49--  https://docs.google.com/spreadsheets/d/1yoHIzDcD62lBmtVf3WheVZuSpW6DwIa03UrPlZIXfiI
Resolving docs.google.com (docs.google.com)... 173.194.217.101, 173.194.217.102, 173.194.217.139, ...
Connecting to docs.google.com (docs.google.com)|173.194.217.101|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://docs.google.com/spreadsheets/d/1yoHIzDcD62lBmtVf3WheVZuSpW6DwIa03UrPlZIXfiI/ [following]
--2020-10-25 15:45:49--  https://docs.google.com/spreadsheets/d/1yoHIzDcD62lBmtVf3WheVZuSpW6DwIa03UrPlZIXfiI/
Reusing existing connection to docs.google.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://docs.google.com/spreadsheets/d/1yoHIzDcD62lBmtVf3WheVZuSpW6DwIa03UrPlZIXfiI/edit [following]
--2020-10-25 15:45:49--  https://docs.google.com/spreadsheets/d/1yoHIzDcD62lBmtVf3WheVZuSpW6DwIa03UrPlZIXfiI/edit
Reusing existing connection to docs.google.com:443.
HTTP request sent, awaiting response

In [ ]:
ls

 1yoHIzDcD62lBmtVf3WheVZuSpW6DwIa03UrPlZIXfiI    'edit?usp=sharing'
 1yoHIzDcD62lBmtVf3WheVZuSpW6DwIa03UrPlZIXfiI.1   sample_data/
 drive/


In [ ]:
!wget https://dboxutja.coursera-apps.org/files/readonly/images.zip


--2020-11-02 08:18:24--  https://dboxutja.coursera-apps.org/files/readonly/images.zip
Resolving dboxutja.coursera-apps.org (dboxutja.coursera-apps.org)... 52.73.213.71, 34.193.180.235
Connecting to dboxutja.coursera-apps.org (dboxutja.coursera-apps.org)|52.73.213.71|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://hub.coursera-apps.org:443/connect/dboxutja?forceRefresh=false&isIframe=false [following]
--2020-11-02 08:18:24--  https://hub.coursera-apps.org/connect/dboxutja?forceRefresh=false&isIframe=false
Resolving hub.coursera-apps.org (hub.coursera-apps.org)... 52.73.213.71, 34.193.180.235
Connecting to hub.coursera-apps.org (hub.coursera-apps.org)|52.73.213.71|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://www.coursera.org:443/workspaces/authenticate/dboxutja?forceRefresh=false&isIframe=false [following]
--2020-11-02 08:18:25--  https://www.coursera.org/workspaces/authenticate/dboxutja?for

In [ ]:
!pip install zipfile36


In [ ]:
import zipfile
zipfile.open('r')
    

AttributeError: ignored

In [4]:
# GPU information
import GPUtil
from tabulate import tabulate
print("="*40, "GPU Details", "="*40)
gpus = GPUtil.getGPUs()
list_gpus = []
for gpu in gpus:
    # get the GPU id
    gpu_id = gpu.id
    # name of GPU
    gpu_name = gpu.name
    # get % percentage of GPU usage of that GPU
    gpu_load = f"{gpu.load*100}%"
    # get free memory in MB format
    gpu_free_memory = f"{gpu.memoryFree}MB"
    # get used memory
    gpu_used_memory = f"{gpu.memoryUsed}MB"
    # get total memory
    gpu_total_memory = f"{gpu.memoryTotal}MB"
    # get GPU temperature in Celsius
    gpu_temperature = f"{gpu.temperature} °C"
    gpu_uuid = gpu.uuid
    list_gpus.append((
        gpu_id, gpu_name, gpu_load, gpu_free_memory, gpu_used_memory,
        gpu_total_memory, gpu_temperature, gpu_uuid
    ))

print(tabulate(list_gpus, headers=("id", "name", "load", "free memory", "used memory", "total memory",
                                   "temperature", "uuid")))

======================================== GPU Details ========================================
id    name    load    free memory    used memory    total memory    temperature    uuid
----  ------  ------  -------------  -------------  --------------  -------------  ------
